print('-------------')
print('Sum')
print('-------------')
num1 = input('Press Enter 1st number to continue... : ')
num2 = input('Press Enter 2nd number to continue... : ')
sum = int(num1) + int(num2)
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))
print('-------------')
